/// 生缺陷儿结局代码表
Class WS.Code.CV0210004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0210004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0210004D</DataLocation>
<DefaultData>CV0210004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0210004D</IdLocation>
<IndexLocation>^WS.Code.CV0210004I</IndexLocation>
<StreamLocation>^WS.Code.CV0210004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
