/// 传染病患者归属代码表
Class WS.Code.CV0201104 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0201104DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0201104D</DataLocation>
<DefaultData>CV0201104DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0201104D</IdLocation>
<IndexLocation>^WS.Code.CV0201104I</IndexLocation>
<StreamLocation>^WS.Code.CV0201104S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
