/// 传染病患者职业代码表
Class WS.Code.CV0201202 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0201202DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0201202D</DataLocation>
<DefaultData>CV0201202DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0201202D</IdLocation>
<IndexLocation>^WS.Code.CV0201202I</IndexLocation>
<StreamLocation>^WS.Code.CV0201202S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
