/// 妊娠终止方式代码表
Class WS.Code.CV0210002 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0210002DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0210002D</DataLocation>
<DefaultData>CV0210002DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0210002D</IdLocation>
<IndexLocation>^WS.Code.CV0210002I</IndexLocation>
<StreamLocation>^WS.Code.CV0210002S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
