/// 出生(分娩)地点类别代码表
Class WS.Code.CV0201102 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0201102DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0201102D</DataLocation>
<DefaultData>CV0201102DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0201102D</IdLocation>
<IndexLocation>^WS.Code.CV0201102I</IndexLocation>
<StreamLocation>^WS.Code.CV0201102S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
