/// 既往常见疾病种类代码表
Class WS.Code.CV0210005 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0210005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0210005D</DataLocation>
<DefaultData>CV0210005DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0210005D</IdLocation>
<IndexLocation>^WS.Code.CV0210005I</IndexLocation>
<StreamLocation>^WS.Code.CV0210005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
