/// 医疗保险类别代码表
Class WS.Code.CV0201204 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0201204DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0201204D</DataLocation>
<DefaultData>CV0201204DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0201204D</IdLocation>
<IndexLocation>^WS.Code.CV0201204I</IndexLocation>
<StreamLocation>^WS.Code.CV0201204S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
