/// 家庭年人均收人代码表
Class WS.Code.CV0201203 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0201203DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0201203D</DataLocation>
<DefaultData>CV0201203DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0201203D</IdLocation>
<IndexLocation>^WS.Code.CV0201203I</IndexLocation>
<StreamLocation>^WS.Code.CV0201203S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
