/// 艾滋病接触史代码表
Class WS.Code.CV0300113 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300113DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300113D</DataLocation>
<DefaultData>CV0300113DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300113D</IdLocation>
<IndexLocation>^WS.Code.CV0300113I</IndexLocation>
<StreamLocation>^WS.Code.CV0300113S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
