/// 吸食烟草种类代码表
Class WS.Code.CV0300103 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300103DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300103D</DataLocation>
<DefaultData>CV0300103DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300103D</IdLocation>
<IndexLocation>^WS.Code.CV0300103I</IndexLocation>
<StreamLocation>^WS.Code.CV0300103S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
