/// 每日饮水工代码表
Class WS.Code.CV0300114 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300114DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300114D</DataLocation>
<DefaultData>CV0300114DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300114D</IdLocation>
<IndexLocation>^WS.Code.CV0300114I</IndexLocation>
<StreamLocation>^WS.Code.CV0300114S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
