/// 接触有害因素类别代码表
Class WS.Code.CV0300403 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300403DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300403D</DataLocation>
<DefaultData>CV0300403DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300403D</IdLocation>
<IndexLocation>^WS.Code.CV0300403I</IndexLocation>
<StreamLocation>^WS.Code.CV0300403S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
