/// 饮食种类表
Class WS.Code.CV0300106 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300106DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300106D</DataLocation>
<DefaultData>CV0300106DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300106D</IdLocation>
<IndexLocation>^WS.Code.CV0300106I</IndexLocation>
<StreamLocation>^WS.Code.CV0300106S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
