/// 受照原因代码表
Class WS.Code.CV0300202 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300202DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300202D</DataLocation>
<DefaultData>CV0300202DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300202D</IdLocation>
<IndexLocation>^WS.Code.CV0300202I</IndexLocation>
<StreamLocation>^WS.Code.CV0300202S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
