/// 厕所类别代码表
Class WS.Code.CV0300304 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300304DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300304D</DataLocation>
<DefaultData>CV0300304DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300304D</IdLocation>
<IndexLocation>^WS.Code.CV0300304I</IndexLocation>
<StreamLocation>^WS.Code.CV0300304S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
