/// 饮酒频率代码表
Class WS.Code.CV0300104 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300104DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300104D</DataLocation>
<DefaultData>CV0300104DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300104D</IdLocation>
<IndexLocation>^WS.Code.CV0300104I</IndexLocation>
<StreamLocation>^WS.Code.CV0300104S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
