/// 环境危险因素暴露类别代码表
Class WS.Code.CV0300301 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300301DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300301D</DataLocation>
<DefaultData>CV0300301DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300301D</IdLocation>
<IndexLocation>^WS.Code.CV0300301I</IndexLocation>
<StreamLocation>^WS.Code.CV0300301S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
