/// 孕早期服药类别代码表
Class WS.Code.CV0300401 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300401DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300401D</DataLocation>
<DefaultData>CV0300401DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300401D</IdLocation>
<IndexLocation>^WS.Code.CV0300401I</IndexLocation>
<StreamLocation>^WS.Code.CV0300401S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
