/// 被动吸烟场所类别代码表
Class WS.Code.CV0300102 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300102DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300102D</DataLocation>
<DefaultData>CV0300102DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300102D</IdLocation>
<IndexLocation>^WS.Code.CV0300102I</IndexLocation>
<StreamLocation>^WS.Code.CV0300102S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
