/// 身体活动频率代码表
Class WS.Code.CV0300111 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300111DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300111D</DataLocation>
<DefaultData>CV0300111DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300111D</IdLocation>
<IndexLocation>^WS.Code.CV0300111I</IndexLocation>
<StreamLocation>^WS.Code.CV0300111S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
