/// 艾滋病患者亲属HIV感染状况代码表
Class WS.Code.CV0300404 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300404DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300404D</DataLocation>
<DefaultData>CV0300404DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300404D</IdLocation>
<IndexLocation>^WS.Code.CV0300404I</IndexLocation>
<StreamLocation>^WS.Code.CV0300404S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
