/// 饮食频率分类代表
Class WS.Code.CV0300108 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300108DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300108D</DataLocation>
<DefaultData>CV0300108DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300108D</IdLocation>
<IndexLocation>^WS.Code.CV0300108I</IndexLocation>
<StreamLocation>^WS.Code.CV0300108S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
