/// 厨房排风设施类别代码表
Class WS.Code.CV0300302 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300302DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300302D</DataLocation>
<DefaultData>CV0300302DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300302D</IdLocation>
<IndexLocation>^WS.Code.CV0300302I</IndexLocation>
<StreamLocation>^WS.Code.CV0300302S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
