/// 患重性精神疾病对家庭社会的影响代码表
Class WS.Code.CV0300112 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300112DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300112D</DataLocation>
<DefaultData>CV0300112DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300112D</IdLocation>
<IndexLocation>^WS.Code.CV0300112I</IndexLocation>
<StreamLocation>^WS.Code.CV0300112S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
