/// 燃料类型类别代码表
Class WS.Code.CV0300303 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300303DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300303D</DataLocation>
<DefaultData>CV0300303DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300303D</IdLocation>
<IndexLocation>^WS.Code.CV0300303I</IndexLocation>
<StreamLocation>^WS.Code.CV0300303S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
