/// 吸烟状态代码表
Class WS.Code.CV0300101 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300101DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300101D</DataLocation>
<DefaultData>CV0300101DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300101D</IdLocation>
<IndexLocation>^WS.Code.CV0300101I</IndexLocation>
<StreamLocation>^WS.Code.CV0300101S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
