/// 每天食用的食物食用频率代码表
Class WS.Code.CV0300109 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300109DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300109D</DataLocation>
<DefaultData>CV0300109DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300109D</IdLocation>
<IndexLocation>^WS.Code.CV0300109I</IndexLocation>
<StreamLocation>^WS.Code.CV0300109S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
