/// 饮水类别代码表
Class WS.Code.CV0300115 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300115DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300115D</DataLocation>
<DefaultData>CV0300115DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300115D</IdLocation>
<IndexLocation>^WS.Code.CV0300115I</IndexLocation>
<StreamLocation>^WS.Code.CV0300115S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
