/// 个人不良行为接触史代码表
Class WS.Code.CV0300116 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300116DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0300116D</DataLocation>
<DefaultData>CV0300116DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0300116D</IdLocation>
<IndexLocation>^WS.Code.CV0300116I</IndexLocation>
<StreamLocation>^WS.Code.CV0300116S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
