/// 老年人健康状态自我评估代码表
Class WS.Code.CV0401013 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401013DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401013D</DataLocation>
<DefaultData>CV0401013DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401013D</IdLocation>
<IndexLocation>^WS.Code.CV0401013I</IndexLocation>
<StreamLocation>^WS.Code.CV0401013S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
