/// 痰检培养结果代码表
Class WS.Code.CV0450014 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450014DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450014D</DataLocation>
<DefaultData>CV0450014DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450014D</IdLocation>
<IndexLocation>^WS.Code.CV0450014I</IndexLocation>
<StreamLocation>^WS.Code.CV0450014S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
