/// 子宫大小代码表
Class WS.Code.CV0410002 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410002DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410002D</DataLocation>
<DefaultData>CV0410002DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410002D</IdLocation>
<IndexLocation>^WS.Code.CV0410002I</IndexLocation>
<StreamLocation>^WS.Code.CV0410002S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
