/// 常用放射诊断检查技术编码表
Class WS.Code.CV0430002 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0430002DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0430002D</DataLocation>
<DefaultData>CV0430002DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0430002D</IdLocation>
<IndexLocation>^WS.Code.CV0430002I</IndexLocation>
<StreamLocation>^WS.Code.CV0430002S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
