/// 伤害发生原因代码表
Class WS.Code.CV0401003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401003D</DataLocation>
<DefaultData>CV0401003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401003D</IdLocation>
<IndexLocation>^WS.Code.CV0401003I</IndexLocation>
<StreamLocation>^WS.Code.CV0401003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
