/// 齿列类别代码
Class WS.Code.CV0410010 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410010DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410010D</DataLocation>
<DefaultData>CV0410010DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410010D</IdLocation>
<IndexLocation>^WS.Code.CV0410010I</IndexLocation>
<StreamLocation>^WS.Code.CV0410010S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
