/// 慢性丝虫病患者症状代码表
Class WS.Code.CV0401008 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401008DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401008D</DataLocation>
<DefaultData>CV0401008DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401008D</IdLocation>
<IndexLocation>^WS.Code.CV0401008I</IndexLocation>
<StreamLocation>^WS.Code.CV0401008S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
