/// 妇科及乳腺不适症状代码表
Class WS.Code.CV0401001 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401001DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401001D</DataLocation>
<DefaultData>CV0401001DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401001D</IdLocation>
<IndexLocation>^WS.Code.CV0401001I</IndexLocation>
<StreamLocation>^WS.Code.CV0401001S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
