/// 药敏试验结果代码表
Class WS.Code.CV0450013 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450013DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450013D</DataLocation>
<DefaultData>CV0450013DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450013D</IdLocation>
<IndexLocation>^WS.Code.CV0450013I</IndexLocation>
<StreamLocation>^WS.Code.CV0450013S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
