/// 阴道细胞学诊断结果代码表
Class WS.Code.CV0450011 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450011DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450011D</DataLocation>
<DefaultData>CV0450011DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450011D</IdLocation>
<IndexLocation>^WS.Code.CV0450011I</IndexLocation>
<StreamLocation>^WS.Code.CV0450011S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
