/// 儿童睡眠质量代码表
Class WS.Code.CV0401010 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401010DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401010D</DataLocation>
<DefaultData>CV0401010DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401010D</IdLocation>
<IndexLocation>^WS.Code.CV0401010I</IndexLocation>
<StreamLocation>^WS.Code.CV0401010S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
