/// 耐药突变检测阳性项目代码表
Class WS.Code.CV0450004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450004D</DataLocation>
<DefaultData>CV0450004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450004D</IdLocation>
<IndexLocation>^WS.Code.CV0450004I</IndexLocation>
<StreamLocation>^WS.Code.CV0450004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
