/// 可疑佝偻病症状代码
Class WS.Code.CV0410021 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410021DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410021D</DataLocation>
<DefaultData>CV0410021DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410021D</IdLocation>
<IndexLocation>^WS.Code.CV0410021I</IndexLocation>
<StreamLocation>^WS.Code.CV0410021S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
