/// 下肢水肿检查结果代码表
Class WS.Code.CV0410014 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410014DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410014D</DataLocation>
<DefaultData>CV0410014DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410014D</IdLocation>
<IndexLocation>^WS.Code.CV0410014I</IndexLocation>
<StreamLocation>^WS.Code.CV0410014S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
