/// 妊娠诊断方法代码表
Class WS.Code.CV0450012 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450012DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450012D</DataLocation>
<DefaultData>CV0450012DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450012D</IdLocation>
<IndexLocation>^WS.Code.CV0450012I</IndexLocation>
<StreamLocation>^WS.Code.CV0450012S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
