/// 血吸虫患者肝实质纤维化程度代码表
Class WS.Code.CV0430001 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0430001DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0430001D</DataLocation>
<DefaultData>CV0430001DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0430001D</IdLocation>
<IndexLocation>^WS.Code.CV0430001I</IndexLocation>
<StreamLocation>^WS.Code.CV0430001S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
