/// 皮肤检查结果代码
Class WS.Code.CV0410004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410004D</DataLocation>
<DefaultData>CV0410004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410004D</IdLocation>
<IndexLocation>^WS.Code.CV0410004I</IndexLocation>
<StreamLocation>^WS.Code.CV0410004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
