/// 疑似结核患者症状代码表
Class WS.Code.CV0401007 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401007DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401007D</DataLocation>
<DefaultData>CV0401007DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401007D</IdLocation>
<IndexLocation>^WS.Code.CV0401007I</IndexLocation>
<StreamLocation>^WS.Code.CV0401007S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
