/// 慢性丝虫病症状发作部位代码
Class WS.Code.CV0410017 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410017DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410017D</DataLocation>
<DefaultData>CV0410017DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410017D</IdLocation>
<IndexLocation>^WS.Code.CV0410017I</IndexLocation>
<StreamLocation>^WS.Code.CV0410017S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
