/// HBV基因分型代码表
Class WS.Code.CV0450002 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450002DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450002D</DataLocation>
<DefaultData>CV0450002DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450002D</IdLocation>
<IndexLocation>^WS.Code.CV0450002I</IndexLocation>
<StreamLocation>^WS.Code.CV0450002S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
