/// 黄疸部位代码
Class WS.Code.CV0410009 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410009DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410009D</DataLocation>
<DefaultData>CV0410009DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410009D</IdLocation>
<IndexLocation>^WS.Code.CV0410009I</IndexLocation>
<StreamLocation>^WS.Code.CV0410009S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
