/// 肛门指诊检查结果代码
Class WS.Code.CV0410013 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410013DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410013D</DataLocation>
<DefaultData>CV0410013DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410013D</IdLocation>
<IndexLocation>^WS.Code.CV0410013I</IndexLocation>
<StreamLocation>^WS.Code.CV0410013S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
