/// 儿童睡眠情况代码表
Class WS.Code.CV0401011 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401011DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401011D</DataLocation>
<DefaultData>CV0401011DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401011D</IdLocation>
<IndexLocation>^WS.Code.CV0401011I</IndexLocation>
<StreamLocation>^WS.Code.CV0401011S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
