/// 伤害部位代码
Class WS.Code.CV0410016 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410016DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410016D</DataLocation>
<DefaultData>CV0410016DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410016D</IdLocation>
<IndexLocation>^WS.Code.CV0410016I</IndexLocation>
<StreamLocation>^WS.Code.CV0410016S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
