/// 血吸虫病抗体检测方法代码表
Class WS.Code.CV0450018 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450018DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450018D</DataLocation>
<DefaultData>CV0450018DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450018D</IdLocation>
<IndexLocation>^WS.Code.CV0450018I</IndexLocation>
<StreamLocation>^WS.Code.CV0450018S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
