/// 采血方式代码表
Class WS.Code.CV0450006 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450006DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450006D</DataLocation>
<DefaultData>CV0450006DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450006D</IdLocation>
<IndexLocation>^WS.Code.CV0450006I</IndexLocation>
<StreamLocation>^WS.Code.CV0450006S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
