/// 足背动脉动博支代码表
Class WS.Code.CV0410015 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410015DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410015D</DataLocation>
<DefaultData>CV0410015DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410015D</IdLocation>
<IndexLocation>^WS.Code.CV0410015I</IndexLocation>
<StreamLocation>^WS.Code.CV0410015S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
