/// Rh血型代码表
Class WS.Code.CV0450020 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450020DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450020D</DataLocation>
<DefaultData>CV0450020DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450020D</IdLocation>
<IndexLocation>^WS.Code.CV0450020I</IndexLocation>
<StreamLocation>^WS.Code.CV0450020S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
