/// 新生儿疾病筛查方法代码表
Class WS.Code.CV0450009 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450009DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450009D</DataLocation>
<DefaultData>CV0450009DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450009D</IdLocation>
<IndexLocation>^WS.Code.CV0450009I</IndexLocation>
<StreamLocation>^WS.Code.CV0450009S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
