/// 采血部位代码表
Class WS.Code.CV0450007 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450007DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450007D</DataLocation>
<DefaultData>CV0450007DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450007D</IdLocation>
<IndexLocation>^WS.Code.CV0450007I</IndexLocation>
<StreamLocation>^WS.Code.CV0450007S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
