/// 儿童体格发育评价代码
Class WS.Code.CV0410020 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410020DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410020D</DataLocation>
<DefaultData>CV0410020DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410020D</IdLocation>
<IndexLocation>^WS.Code.CV0410020I</IndexLocation>
<StreamLocation>^WS.Code.CV0410020S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
