/// 淋巴结检查结果代码
Class WS.Code.CV0410011 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410011DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410011D</DataLocation>
<DefaultData>CV0410011DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410011D</IdLocation>
<IndexLocation>^WS.Code.CV0410011I</IndexLocation>
<StreamLocation>^WS.Code.CV0410011S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
