/// 老年人生活处理能力自我评估代码表
Class WS.Code.CV0401014 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401014DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401014D</DataLocation>
<DefaultData>CV0401014DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401014D</IdLocation>
<IndexLocation>^WS.Code.CV0401014I</IndexLocation>
<StreamLocation>^WS.Code.CV0401014S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
