/// 巩膜检查结果代码
Class WS.Code.CV0410006 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410006DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410006D</DataLocation>
<DefaultData>CV0410006DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410006D</IdLocation>
<IndexLocation>^WS.Code.CV0410006I</IndexLocation>
<StreamLocation>^WS.Code.CV0410006S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
