/// 血吸虫病虫卵检测方法代码表
Class WS.Code.CV0450016 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450016DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450016D</DataLocation>
<DefaultData>CV0450016DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450016D</IdLocation>
<IndexLocation>^WS.Code.CV0450016I</IndexLocation>
<StreamLocation>^WS.Code.CV0450016S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
