/// 浮肿状况代码
Class WS.Code.CV0410005 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410005D</DataLocation>
<DefaultData>CV0410005DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410005D</IdLocation>
<IndexLocation>^WS.Code.CV0410005I</IndexLocation>
<StreamLocation>^WS.Code.CV0410005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
