/// 伤害意图类别代码表
Class WS.Code.CV0401004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401004D</DataLocation>
<DefaultData>CV0401004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401004D</IdLocation>
<IndexLocation>^WS.Code.CV0401004I</IndexLocation>
<StreamLocation>^WS.Code.CV0401004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
