/// 尿实验室定性检测结果代码表
Class WS.Code.CV0450015 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450015DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450015D</DataLocation>
<DefaultData>CV0450015DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450015D</IdLocation>
<IndexLocation>^WS.Code.CV0450015I</IndexLocation>
<StreamLocation>^WS.Code.CV0450015S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
