/// 可疑佝偻病体征代码
Class WS.Code.CV0410022 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410022DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410022D</DataLocation>
<DefaultData>CV0410022DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410022D</IdLocation>
<IndexLocation>^WS.Code.CV0410022I</IndexLocation>
<StreamLocation>^WS.Code.CV0410022S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
