/// 前囟张力代码
Class WS.Code.CV0410018 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410018DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410018D</DataLocation>
<DefaultData>CV0410018DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410018D</IdLocation>
<IndexLocation>^WS.Code.CV0410018I</IndexLocation>
<StreamLocation>^WS.Code.CV0410018S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
