/// 阴道分泌物清洁度代码表
Class WS.Code.CV0450010 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450010DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450010D</DataLocation>
<DefaultData>CV0450010DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450010D</IdLocation>
<IndexLocation>^WS.Code.CV0450010I</IndexLocation>
<StreamLocation>^WS.Code.CV0450010S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
