/// HBV血清型代码表
Class WS.Code.CV0450003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450003D</DataLocation>
<DefaultData>CV0450003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450003D</IdLocation>
<IndexLocation>^WS.Code.CV0450003I</IndexLocation>
<StreamLocation>^WS.Code.CV0450003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
