/// 脐带检查结果代码表
Class WS.Code.CV0410019 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410019DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410019D</DataLocation>
<DefaultData>CV0410019DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410019D</IdLocation>
<IndexLocation>^WS.Code.CV0410019I</IndexLocation>
<StreamLocation>^WS.Code.CV0410019S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
