/// 伤害发生地点代码表
Class WS.Code.CV0401005 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0401005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0401005D</DataLocation>
<DefaultData>CV0401005DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0401005D</IdLocation>
<IndexLocation>^WS.Code.CV0401005I</IndexLocation>
<StreamLocation>^WS.Code.CV0401005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
