/// 儿童面色代码
Class WS.Code.CV0410008 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0410008DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0410008D</DataLocation>
<DefaultData>CV0410008DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0410008D</IdLocation>
<IndexLocation>^WS.Code.CV0410008I</IndexLocation>
<StreamLocation>^WS.Code.CV0410008S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
