/// ABO血型代码表
Class WS.Code.CV0450005 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0450005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0450005D</DataLocation>
<DefaultData>CV0450005DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0450005D</IdLocation>
<IndexLocation>^WS.Code.CV0450005I</IndexLocation>
<StreamLocation>^WS.Code.CV0450005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
