/// 放射性疾病的分度代码表
Class WS.Code.CV0501033 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501033DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501033D</DataLocation>
<DefaultData>CV0501033DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501033D</IdLocation>
<IndexLocation>^WS.Code.CV0501033I</IndexLocation>
<StreamLocation>^WS.Code.CV0501033S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
