/// 儿童体弱原因类别代码表
Class WS.Code.CV0510007 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510007DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510007D</DataLocation>
<DefaultData>CV0510007DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510007D</IdLocation>
<IndexLocation>^WS.Code.CV0510007I</IndexLocation>
<StreamLocation>^WS.Code.CV0510007S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
