/// 放射性疾病的分期代码表
Class WS.Code.CV0501034 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501034DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501034D</DataLocation>
<DefaultData>CV0501034DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501034D</IdLocation>
<IndexLocation>^WS.Code.CV0501034I</IndexLocation>
<StreamLocation>^WS.Code.CV0501034S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
