/// 乳糜尿发作诱因代码表
Class WS.Code.CV0501003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501003D</DataLocation>
<DefaultData>CV0501003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501003D</IdLocation>
<IndexLocation>^WS.Code.CV0501003I</IndexLocation>
<StreamLocation>^WS.Code.CV0501003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
