/// 随访评价结果代码表
Class WS.Code.CV0510012 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510012DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510012D</DataLocation>
<DefaultData>CV0510012DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510012D</IdLocation>
<IndexLocation>^WS.Code.CV0510012I</IndexLocation>
<StreamLocation>^WS.Code.CV0510012S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
