/// 胎方位代码表
Class WS.Code.CV0501007 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501007DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501007D</DataLocation>
<DefaultData>CV0501007DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501007D</IdLocation>
<IndexLocation>^WS.Code.CV0501007I</IndexLocation>
<StreamLocation>^WS.Code.CV0501007S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
