/// 新生儿黄疸程度代码表
Class WS.Code.CV0501012 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501012DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501012D</DataLocation>
<DefaultData>CV0501012DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501012D</IdLocation>
<IndexLocation>^WS.Code.CV0501012I</IndexLocation>
<StreamLocation>^WS.Code.CV0501012S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
