/// 残疾情况代码表
Class WS.Code.CV0510001 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510001DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510001D</DataLocation>
<DefaultData>CV0510001DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510001D</IdLocation>
<IndexLocation>^WS.Code.CV0510001I</IndexLocation>
<StreamLocation>^WS.Code.CV0510001S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
