/// 会阴裂伤情况代码表
Class WS.Code.CV0501010 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501010DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501010D</DataLocation>
<DefaultData>CV0501010DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501010D</IdLocation>
<IndexLocation>^WS.Code.CV0501010I</IndexLocation>
<StreamLocation>^WS.Code.CV0501010S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
