/// 病情转归代码表
Class WS.Code.CV0510010 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510010DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510010D</DataLocation>
<DefaultData>CV0510010DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510010D</IdLocation>
<IndexLocation>^WS.Code.CV0510010I</IndexLocation>
<StreamLocation>^WS.Code.CV0510010S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
