/// 慢性HBV感染临床诊断分类代码表
Class WS.Code.CV0501029 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501029DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501029D</DataLocation>
<DefaultData>CV0501029DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501029D</IdLocation>
<IndexLocation>^WS.Code.CV0501029I</IndexLocation>
<StreamLocation>^WS.Code.CV0501029S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
