/// 疑似食源性异常病例（健康事件）可疑病因代码表
Class WS.Code.CV0510017 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510017DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510017D</DataLocation>
<DefaultData>CV0510017DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510017D</IdLocation>
<IndexLocation>^WS.Code.CV0510017I</IndexLocation>
<StreamLocation>^WS.Code.CV0510017S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
