/// 血吸虫病患者劳动能力分级代码表
Class WS.Code.CV0510008 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510008DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510008D</DataLocation>
<DefaultData>CV0510008DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510008D</IdLocation>
<IndexLocation>^WS.Code.CV0510008I</IndexLocation>
<StreamLocation>^WS.Code.CV0510008S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
