/// 职业健康检查结论代码表
Class WS.Code.CV0510009 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510009DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510009D</DataLocation>
<DefaultData>CV0510009DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510009D</IdLocation>
<IndexLocation>^WS.Code.CV0510009I</IndexLocation>
<StreamLocation>^WS.Code.CV0510009S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
