/// 儿童生长发育评价结果代码表
Class WS.Code.CV0510006 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510006DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510006D</DataLocation>
<DefaultData>CV0510006DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510006D</IdLocation>
<IndexLocation>^WS.Code.CV0510006I</IndexLocation>
<StreamLocation>^WS.Code.CV0510006S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
