/// 出生缺陷类别代码表
Class WS.Code.CV0501016 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501016DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501016D</DataLocation>
<DefaultData>CV0501016DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501016D</IdLocation>
<IndexLocation>^WS.Code.CV0501016I</IndexLocation>
<StreamLocation>^WS.Code.CV0501016S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
