/// 重性精神疾病名称代码表
Class WS.Code.CV0501036 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501036DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501036D</DataLocation>
<DefaultData>CV0501036DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501036D</IdLocation>
<IndexLocation>^WS.Code.CV0501036I</IndexLocation>
<StreamLocation>^WS.Code.CV0501036S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
