/// 诊断结核病类型代码表
Class WS.Code.CV0501020 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501020DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501020D</DataLocation>
<DefaultData>CV0501020DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501020D</IdLocation>
<IndexLocation>^WS.Code.CV0501020I</IndexLocation>
<StreamLocation>^WS.Code.CV0501020S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
