/// 5岁以下儿童死因分类代码表
Class WS.Code.CV0501039 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501039DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501039D</DataLocation>
<DefaultData>CV0501039DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501039D</IdLocation>
<IndexLocation>^WS.Code.CV0501039I</IndexLocation>
<StreamLocation>^WS.Code.CV0501039S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
