/// 血吸虫病感染方式代码表
Class WS.Code.CV0501023 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501023DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501023D</DataLocation>
<DefaultData>CV0501023DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501023D</IdLocation>
<IndexLocation>^WS.Code.CV0501023I</IndexLocation>
<StreamLocation>^WS.Code.CV0501023S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
