/// 婚前医学检查结果代码表
Class WS.Code.CV0510005 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510005D</DataLocation>
<DefaultData>CV0510005DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510005D</IdLocation>
<IndexLocation>^WS.Code.CV0510005I</IndexLocation>
<StreamLocation>^WS.Code.CV0510005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
