/// 血吸虫病诊断状态代码表
Class WS.Code.CV0501024 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501024DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501024D</DataLocation>
<DefaultData>CV0501024DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501024D</IdLocation>
<IndexLocation>^WS.Code.CV0501024I</IndexLocation>
<StreamLocation>^WS.Code.CV0501024S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
