/// 重性精神疾病患者危害性分级代码表
Class WS.Code.CV0510013 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510013DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510013D</DataLocation>
<DefaultData>CV0510013DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510013D</IdLocation>
<IndexLocation>^WS.Code.CV0510013I</IndexLocation>
<StreamLocation>^WS.Code.CV0510013S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
