/// 诊断状态代码表
Class WS.Code.CV0501002 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501002DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501002D</DataLocation>
<DefaultData>CV0501002DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501002D</IdLocation>
<IndexLocation>^WS.Code.CV0501002I</IndexLocation>
<StreamLocation>^WS.Code.CV0501002S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
