/// 慢性乙型肝炎的临床分级代码表
Class WS.Code.CV0501030 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501030DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501030D</DataLocation>
<DefaultData>CV0501030DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501030D</IdLocation>
<IndexLocation>^WS.Code.CV0501030I</IndexLocation>
<StreamLocation>^WS.Code.CV0501030S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
