/// 影响孕产妇死亡的主要因素代码表
Class WS.Code.CV0510016 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510016DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510016D</DataLocation>
<DefaultData>CV0510016DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510016D</IdLocation>
<IndexLocation>^WS.Code.CV0510016I</IndexLocation>
<StreamLocation>^WS.Code.CV0510016S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
