/// 预防接种后不良反应临床诊断代码表
Class WS.Code.CV0501032 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501032DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501032D</DataLocation>
<DefaultData>CV0501032DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501032D</IdLocation>
<IndexLocation>^WS.Code.CV0501032I</IndexLocation>
<StreamLocation>^WS.Code.CV0501032S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
