/// 死亡最高诊断依据类别代码表
Class WS.Code.CV0501037 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501037DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501037D</DataLocation>
<DefaultData>CV0501037DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501037D</IdLocation>
<IndexLocation>^WS.Code.CV0501037I</IndexLocation>
<StreamLocation>^WS.Code.CV0501037S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
