/// 伤害性质代码表
Class WS.Code.CV0501004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501004D</DataLocation>
<DefaultData>CV0501004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501004D</IdLocation>
<IndexLocation>^WS.Code.CV0501004I</IndexLocation>
<StreamLocation>^WS.Code.CV0501004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
