/// 疑似食源性异常病例（健康事件）报告卡上报原因代码表
Class WS.Code.CV0510018 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510018DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510018D</DataLocation>
<DefaultData>CV0510018DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510018D</IdLocation>
<IndexLocation>^WS.Code.CV0510018I</IndexLocation>
<StreamLocation>^WS.Code.CV0510018S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
