/// 过敏源代码表
Class WS.Code.CV0501038 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501038DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501038D</DataLocation>
<DefaultData>CV0501038DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501038D</IdLocation>
<IndexLocation>^WS.Code.CV0501038I</IndexLocation>
<StreamLocation>^WS.Code.CV0501038S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
