/// 血吸虫病合并症代码表
Class WS.Code.CV0501022 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501022DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501022D</DataLocation>
<DefaultData>CV0501022DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501022D</IdLocation>
<IndexLocation>^WS.Code.CV0501022I</IndexLocation>
<StreamLocation>^WS.Code.CV0501022S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
