/// 出生缺陷确诊时间类别代码表
Class WS.Code.CV0501015 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501015DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501015D</DataLocation>
<DefaultData>CV0501015DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501015D</IdLocation>
<IndexLocation>^WS.Code.CV0501015I</IndexLocation>
<StreamLocation>^WS.Code.CV0501015S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
