/// 肺结核诊断结果代码表
Class WS.Code.CV0501021 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501021DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501021D</DataLocation>
<DefaultData>CV0501021DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501021D</IdLocation>
<IndexLocation>^WS.Code.CV0501021I</IndexLocation>
<StreamLocation>^WS.Code.CV0501021S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
