/// 胎先露代码表
Class WS.Code.CV0501008 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501008DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501008D</DataLocation>
<DefaultData>CV0501008DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501008D</IdLocation>
<IndexLocation>^WS.Code.CV0501008I</IndexLocation>
<StreamLocation>^WS.Code.CV0501008S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
