/// 新生儿并发症代码表
Class WS.Code.CV0501013 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501013DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501013D</DataLocation>
<DefaultData>CV0501013DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501013D</IdLocation>
<IndexLocation>^WS.Code.CV0501013I</IndexLocation>
<StreamLocation>^WS.Code.CV0501013S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
