/// 重性精神疾病患者社会功能情况分类代码表
Class WS.Code.CV0510003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510003D</DataLocation>
<DefaultData>CV0510003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510003D</IdLocation>
<IndexLocation>^WS.Code.CV0510003I</IndexLocation>
<StreamLocation>^WS.Code.CV0510003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
