/// 病毒性肝炎类型代码表
Class WS.Code.CV0501028 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0501028DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0501028D</DataLocation>
<DefaultData>CV0501028DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0501028D</IdLocation>
<IndexLocation>^WS.Code.CV0501028I</IndexLocation>
<StreamLocation>^WS.Code.CV0501028S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
