/// 劳动能力评定分级代码表
Class WS.Code.CV0510004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0510004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0510004D</DataLocation>
<DefaultData>CV0510004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0510004D</IdLocation>
<IndexLocation>^WS.Code.CV0510004I</IndexLocation>
<StreamLocation>^WS.Code.CV0510004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
