/// 儿童预防母婴传播干预措施代码表
Class WS.Code.CV0600214 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600214DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600214D</DataLocation>
<DefaultData>CV0600214DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600214D</IdLocation>
<IndexLocation>^WS.Code.CV0600214I</IndexLocation>
<StreamLocation>^WS.Code.CV0600214S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
