/// 乙肝疫苗接种剂量代码表
Class WS.Code.CV0600109 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600109DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600109D</DataLocation>
<DefaultData>CV0600109DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600109D</IdLocation>
<IndexLocation>^WS.Code.CV0600109I</IndexLocation>
<StreamLocation>^WS.Code.CV0600109S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
