/// 抗结核治疗停止原因代码表
Class WS.Code.CV0600115 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600115DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600115D</DataLocation>
<DefaultData>CV0600115DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600115D</IdLocation>
<IndexLocation>^WS.Code.CV0600115I</IndexLocation>
<StreamLocation>^WS.Code.CV0600115S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
