/// 精神康复措施代码表
Class WS.Code.CV0600209 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600209DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600209D</DataLocation>
<DefaultData>CV0600209DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600209D</IdLocation>
<IndexLocation>^WS.Code.CV0600209I</IndexLocation>
<StreamLocation>^WS.Code.CV0600209S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
