/// 宫内节育器放置时间代码表
Class WS.Code.CV0600104 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600104DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600104D</DataLocation>
<DefaultData>CV0600104DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600104D</IdLocation>
<IndexLocation>^WS.Code.CV0600104I</IndexLocation>
<StreamLocation>^WS.Code.CV0600104S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
