/// 儿童健康指导类别代码表
Class WS.Code.CV0600217 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600217DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600217D</DataLocation>
<DefaultData>CV0600217DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600217D</IdLocation>
<IndexLocation>^WS.Code.CV0600217I</IndexLocation>
<StreamLocation>^WS.Code.CV0600217S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
