/// 随访周期建议代码表
Class WS.Code.CV0600208 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600208DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600208D</DataLocation>
<DefaultData>CV0600208DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600208D</IdLocation>
<IndexLocation>^WS.Code.CV0600208I</IndexLocation>
<StreamLocation>^WS.Code.CV0600208S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
