/// 输卵管结扎手术方式代码表
Class WS.Code.CV0600106 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600106DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600106D</DataLocation>
<DefaultData>CV0600106DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600106D</IdLocation>
<IndexLocation>^WS.Code.CV0600106I</IndexLocation>
<StreamLocation>^WS.Code.CV0600106S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
