/// 乙肝治疗方法代码表
Class WS.Code.CV0600112 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600112DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600112D</DataLocation>
<DefaultData>CV0600112DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600112D</IdLocation>
<IndexLocation>^WS.Code.CV0600112I</IndexLocation>
<StreamLocation>^WS.Code.CV0600112S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
