/// 婴幼儿添加辅食种类代码表
Class WS.Code.CV0600216 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600216DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600216D</DataLocation>
<DefaultData>CV0600216DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600216D</IdLocation>
<IndexLocation>^WS.Code.CV0600216I</IndexLocation>
<StreamLocation>^WS.Code.CV0600216S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
