/// 新生儿抢救方法代码表
Class WS.Code.CV0600108 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600108DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600108D</DataLocation>
<DefaultData>CV0600108DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600108D</IdLocation>
<IndexLocation>^WS.Code.CV0600108I</IndexLocation>
<StreamLocation>^WS.Code.CV0600108S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
