/// 戒烟方法类别代码表
Class WS.Code.CV0600204 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600204DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600204D</DataLocation>
<DefaultData>CV0600204DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600204D</IdLocation>
<IndexLocation>^WS.Code.CV0600204I</IndexLocation>
<StreamLocation>^WS.Code.CV0600204S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
