/// 肿瘤患者指导内容代码表
Class WS.Code.CV0600206 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600206DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600206D</DataLocation>
<DefaultData>CV0600206DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600206D</IdLocation>
<IndexLocation>^WS.Code.CV0600206I</IndexLocation>
<StreamLocation>^WS.Code.CV0600206S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
