/// 乙肝抗病毒治疗的基本药物代码表
Class WS.Code.CV0600110 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600110DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600110D</DataLocation>
<DefaultData>CV0600110DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600110D</IdLocation>
<IndexLocation>^WS.Code.CV0600110I</IndexLocation>
<StreamLocation>^WS.Code.CV0600110S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
