/// 皮下埋植剂埋植时期代码表
Class WS.Code.CV0600105 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600105DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600105D</DataLocation>
<DefaultData>CV0600105DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600105D</IdLocation>
<IndexLocation>^WS.Code.CV0600105I</IndexLocation>
<StreamLocation>^WS.Code.CV0600105S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
