/// 抗结核化疗方案代码表
Class WS.Code.CV0600114 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600114DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600114D</DataLocation>
<DefaultData>CV0600114DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600114D</IdLocation>
<IndexLocation>^WS.Code.CV0600114I</IndexLocation>
<StreamLocation>^WS.Code.CV0600114S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
