/// 婚检医学意见代码表
Class WS.Code.CV0600210 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600210DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600210D</DataLocation>
<DefaultData>CV0600210DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600210D</IdLocation>
<IndexLocation>^WS.Code.CV0600210I</IndexLocation>
<StreamLocation>^WS.Code.CV0600210S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
