/// 危险因素控制建议代码表
Class WS.Code.CV0600218 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600218DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600218D</DataLocation>
<DefaultData>CV0600218DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600218D</IdLocation>
<IndexLocation>^WS.Code.CV0600218I</IndexLocation>
<StreamLocation>^WS.Code.CV0600218S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
