/// 结核患者管理方式代码表
Class WS.Code.CV0600117 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0600117DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0600117D</DataLocation>
<DefaultData>CV0600117DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0600117D</IdLocation>
<IndexLocation>^WS.Code.CV0600117I</IndexLocation>
<StreamLocation>^WS.Code.CV0600117S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
