/// 医疗费用来源类别代码表
Class WS.Code.CV0710003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0710003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0710003D</DataLocation>
<DefaultData>CV0710003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0710003D</IdLocation>
<IndexLocation>^WS.Code.CV0710003I</IndexLocation>
<StreamLocation>^WS.Code.CV0710003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
