/// 助产人员类别代码表
Class WS.Code.CV0830004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0830004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0830004D</DataLocation>
<DefaultData>CV0830004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0830004D</IdLocation>
<IndexLocation>^WS.Code.CV0830004I</IndexLocation>
<StreamLocation>^WS.Code.CV0830004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
