/// 药敏试验药物代码表
Class WS.Code.CV0850003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0850003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0850003D</DataLocation>
<DefaultData>CV0850003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0850003D</IdLocation>
<IndexLocation>^WS.Code.CV0850003I</IndexLocation>
<StreamLocation>^WS.Code.CV0850003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
