/// 血吸虫病诊断（治疗）机构级别代码表
Class WS.Code.CV0810006 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0810006DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0810006D</DataLocation>
<DefaultData>CV0810006DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0810006D</IdLocation>
<IndexLocation>^WS.Code.CV0810006I</IndexLocation>
<StreamLocation>^WS.Code.CV0810006S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
