/// 主要致死疾病的最高诊断机构级别代码表
Class WS.Code.CV0810004 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0810004DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0810004D</DataLocation>
<DefaultData>CV0810004DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0810004D</IdLocation>
<IndexLocation>^WS.Code.CV0810004I</IndexLocation>
<StreamLocation>^WS.Code.CV0810004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
