/// 专业技术职务类别代码表
Class WS.Code.CV0830005 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0830005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0830005D</DataLocation>
<DefaultData>CV0830005DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0830005D</IdLocation>
<IndexLocation>^WS.Code.CV0830005I</IndexLocation>
<StreamLocation>^WS.Code.CV0830005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
