/// 肿瘤诊疗机构代码表
Class WS.Code.CV0810005 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0810005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0810005D</DataLocation>
<DefaultData>CV0810005DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0810005D</IdLocation>
<IndexLocation>^WS.Code.CV0810005I</IndexLocation>
<StreamLocation>^WS.Code.CV0810005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
