/// 监督员执业范围代码表
Class WS.Code.CV0830003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0830003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0830003D</DataLocation>
<DefaultData>CV0830003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0830003D</IdLocation>
<IndexLocation>^WS.Code.CV0830003I</IndexLocation>
<StreamLocation>^WS.Code.CV0830003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
