/// 交通工具代码表
Class WS.Code.CV0850102 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0850102DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0850102D</DataLocation>
<DefaultData>CV0850102DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0850102D</IdLocation>
<IndexLocation>^WS.Code.CV0850102I</IndexLocation>
<StreamLocation>^WS.Code.CV0850102S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
