/// 监督机构科室代码表
Class WS.Code.CV0810003 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0810003DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0810003D</DataLocation>
<DefaultData>CV0810003DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0810003D</IdLocation>
<IndexLocation>^WS.Code.CV0810003I</IndexLocation>
<StreamLocation>^WS.Code.CV0810003S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
