/// 卫生监督机构行政级别代码表
Class WS.Code.CV0810002 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0810002DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0810002D</DataLocation>
<DefaultData>CV0810002DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0810002D</IdLocation>
<IndexLocation>^WS.Code.CV0810002I</IndexLocation>
<StreamLocation>^WS.Code.CV0810002S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
