/// 药物剂型代码表
Class WS.Code.CV0850002 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0850002DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0850002D</DataLocation>
<DefaultData>CV0850002DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0850002D</IdLocation>
<IndexLocation>^WS.Code.CV0850002I</IndexLocation>
<StreamLocation>^WS.Code.CV0850002S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
