/// 卫生监督机构人员编制类别代码表
Class WS.Code.CV0830001 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0830001DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0830001D</DataLocation>
<DefaultData>CV0830001DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0830001D</IdLocation>
<IndexLocation>^WS.Code.CV0830001I</IndexLocation>
<StreamLocation>^WS.Code.CV0830001S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
