/// 许可类别代码表
Class WS.Code.CV0900218 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900218DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900218D</DataLocation>
<DefaultData>CV0900218DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900218D</IdLocation>
<IndexLocation>^WS.Code.CV0900218I</IndexLocation>
<StreamLocation>^WS.Code.CV0900218S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
