/// 卫生监督量化分级管理等级评定情况代码表
Class WS.Code.CV0900201 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900201DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900201D</DataLocation>
<DefaultData>CV0900201DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900201D</IdLocation>
<IndexLocation>^WS.Code.CV0900201I</IndexLocation>
<StreamLocation>^WS.Code.CV0900201S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
