/// 卫生行政处罚结果及行政措施代码表
Class WS.Code.CV0900204 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900204DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900204D</DataLocation>
<DefaultData>CV0900204DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900204D</IdLocation>
<IndexLocation>^WS.Code.CV0900204I</IndexLocation>
<StreamLocation>^WS.Code.CV0900204S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
