/// 职业卫生违法事实代码表
Class WS.Code.CV0900207 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900207DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900207D</DataLocation>
<DefaultData>CV0900207DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900207D</IdLocation>
<IndexLocation>^WS.Code.CV0900207I</IndexLocation>
<StreamLocation>^WS.Code.CV0900207S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
