/// 资产与负债代码表
Class WS.Code.CV0900402 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900402DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900402D</DataLocation>
<DefaultData>CV0900402DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900402D</IdLocation>
<IndexLocation>^WS.Code.CV0900402I</IndexLocation>
<StreamLocation>^WS.Code.CV0900402S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
