/// 卫生监督检查与行政处罚专业类别代码表
Class WS.Code.CV0900203 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900203DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900203D</DataLocation>
<DefaultData>CV0900203DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900203D</IdLocation>
<IndexLocation>^WS.Code.CV0900203I</IndexLocation>
<StreamLocation>^WS.Code.CV0900203S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
