/// 收入与支出代码表
Class WS.Code.CV0900401 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900401DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900401D</DataLocation>
<DefaultData>CV0900401DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900401D</IdLocation>
<IndexLocation>^WS.Code.CV0900401I</IndexLocation>
<StreamLocation>^WS.Code.CV0900401S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
