/// 生活饮用水消毒方式代码表
Class WS.Code.CV0900107 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900107DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900107D</DataLocation>
<DefaultData>CV0900107DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900107D</IdLocation>
<IndexLocation>^WS.Code.CV0900107I</IndexLocation>
<StreamLocation>^WS.Code.CV0900107S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
