/// 放射性同位素和射线装置的种类代码表
Class WS.Code.CV0900112 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900112DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900112D</DataLocation>
<DefaultData>CV0900112DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900112D</IdLocation>
<IndexLocation>^WS.Code.CV0900112I</IndexLocation>
<StreamLocation>^WS.Code.CV0900112S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
