/// 职业病建设项目审核代码表
Class WS.Code.CV0900103 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900103DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900103D</DataLocation>
<DefaultData>CV0900103DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900103D</IdLocation>
<IndexLocation>^WS.Code.CV0900103I</IndexLocation>
<StreamLocation>^WS.Code.CV0900103S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
