/// 学校卫生违法事实代码表
Class WS.Code.CV0900210 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900210DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900210D</DataLocation>
<DefaultData>CV0900210DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900210D</IdLocation>
<IndexLocation>^WS.Code.CV0900210I</IndexLocation>
<StreamLocation>^WS.Code.CV0900210S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
