/// 公共场所违法事实代码表
Class WS.Code.CV0900205 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900205DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900205D</DataLocation>
<DefaultData>CV0900205DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900205D</IdLocation>
<IndexLocation>^WS.Code.CV0900205I</IndexLocation>
<StreamLocation>^WS.Code.CV0900205S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
