/// 职业卫生技术服务业务范围代码表
Class WS.Code.CV0900110 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900110DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900110D</DataLocation>
<DefaultData>CV0900110DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900110D</IdLocation>
<IndexLocation>^WS.Code.CV0900110I</IndexLocation>
<StreamLocation>^WS.Code.CV0900110S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
