/// 医疗卫生违法事实代码表
Class WS.Code.CV0900211 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900211DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900211D</DataLocation>
<DefaultData>CV0900211DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900211D</IdLocation>
<IndexLocation>^WS.Code.CV0900211I</IndexLocation>
<StreamLocation>^WS.Code.CV0900211S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
