/// 采供血卫生违法事实代码表
Class WS.Code.CV0900213 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900213DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900213D</DataLocation>
<DefaultData>CV0900213DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900213D</IdLocation>
<IndexLocation>^WS.Code.CV0900213I</IndexLocation>
<StreamLocation>^WS.Code.CV0900213S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
