/// 卫生监督检查与行政处罚查处案件来源代码表
Class WS.Code.CV0900202 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900202DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900202D</DataLocation>
<DefaultData>CV0900202DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900202D</IdLocation>
<IndexLocation>^WS.Code.CV0900202I</IndexLocation>
<StreamLocation>^WS.Code.CV0900202S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
