/// 资质等级代码表
Class WS.Code.CV0900111 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900111DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900111D</DataLocation>
<DefaultData>CV0900111DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900111D</IdLocation>
<IndexLocation>^WS.Code.CV0900111I</IndexLocation>
<StreamLocation>^WS.Code.CV0900111S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
