/// 职业性健康监护体检类别代码表
Class WS.Code.CV0900109 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900109DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900109D</DataLocation>
<DefaultData>CV0900109DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900109D</IdLocation>
<IndexLocation>^WS.Code.CV0900109I</IndexLocation>
<StreamLocation>^WS.Code.CV0900109S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
