/// 饮用水类别代码表
Class WS.Code.CV0900104 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900104DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900104D</DataLocation>
<DefaultData>CV0900104DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900104D</IdLocation>
<IndexLocation>^WS.Code.CV0900104I</IndexLocation>
<StreamLocation>^WS.Code.CV0900104S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
