/// 卫生监督证书类别代码表
Class WS.Code.CV0900217 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900217DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900217D</DataLocation>
<DefaultData>CV0900217DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900217D</IdLocation>
<IndexLocation>^WS.Code.CV0900217I</IndexLocation>
<StreamLocation>^WS.Code.CV0900217S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
