/// 校内辅助设施类别代码表
Class WS.Code.CV0900209 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900209DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900209D</DataLocation>
<DefaultData>CV0900209DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900209D</IdLocation>
<IndexLocation>^WS.Code.CV0900209I</IndexLocation>
<StreamLocation>^WS.Code.CV0900209S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
