/// 水源水类型代码表
Class WS.Code.CV0900105 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900105DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900105D</DataLocation>
<DefaultData>CV0900105DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900105D</IdLocation>
<IndexLocation>^WS.Code.CV0900105I</IndexLocation>
<StreamLocation>^WS.Code.CV0900105S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
