/// 卫生监督对象类别代码表
Class WS.Code.CV0900101 Extends (%Persistent, WS.Code.Abstract) [ Inheritance = right, ProcedureBlock ]
{

Storage Default
{
<Data name="CV0900101DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>code</Value>
</Value>
<Value name="3">
<Value>displayName</Value>
</Value>
</Data>
<DataLocation>^WS.Code.CV0900101D</DataLocation>
<DefaultData>CV0900101DefaultData</DefaultData>
<IdLocation>^WS.Code.CV0900101D</IdLocation>
<IndexLocation>^WS.Code.CV0900101I</IndexLocation>
<StreamLocation>^WS.Code.CV0900101S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
