Class WS.Document.C0010.C0010 Extends (%Persistent, %XML.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Storage Default
{
<Data name="C0010DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^WS.Document.C0010.C0010D</DataLocation>
<DefaultData>C0010DefaultData</DefaultData>
<IdLocation>^WS.Document.C0010.C0010D</IdLocation>
<IndexLocation>^WS.Document.C0010.C0010I</IndexLocation>
<StreamLocation>^WS.Document.C0010.C0010S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
