Class WS.Document.C0009.C0009 Extends (%Persistent, %XML.Adaptor)
{

Storage Default
{
<Data name="C0009DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^WS.Document.C0009.C0009D</DataLocation>
<DefaultData>C0009DefaultData</DefaultData>
<IdLocation>^WS.Document.C0009.C0009D</IdLocation>
<IndexLocation>^WS.Document.C0009.C0009I</IndexLocation>
<StreamLocation>^WS.Document.C0009.C0009S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
