Class WS.Document.Set.relatedDocument Extends (%SerialObject, %XML.Adaptor)
{

Property parentDcocument As %String;

Property id As %String;

Property setId As %String;

Property versionNumber As %String;

Storage Default
{
<Data name="relatedDocumentState">
<Value name="1">
<Value>parentDcocument</Value>
</Value>
<Value name="2">
<Value>id</Value>
</Value>
<Value name="3">
<Value>setId</Value>
</Value>
<Value name="4">
<Value>versionNumber</Value>
</Value>
</Data>
<State>relatedDocumentState</State>
<StreamLocation>^WS.Documen3922.relatedDocu9B72S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
