Class WS.Document.C0005.C0005 Extends (%Persistent, %XML.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Storage Default
{
<Data name="C0005DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^WS.Document.C0005.C0005D</DataLocation>
<DefaultData>C0005DefaultData</DefaultData>
<IdLocation>^WS.Document.C0005.C0005D</IdLocation>
<IndexLocation>^WS.Document.C0005.C0005I</IndexLocation>
<StreamLocation>^WS.Document.C0005.C0005S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
