Class WS.Document.C0008.C0008 Extends (%Persistent, %XML.Adaptor) [ Inheritance = right, Not ProcedureBlock ]
{

Storage Default
{
<Data name="C0008DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^WS.Document.C0008.C0008D</DataLocation>
<DefaultData>C0008DefaultData</DefaultData>
<IdLocation>^WS.Document.C0008.C0008D</IdLocation>
<IndexLocation>^WS.Document.C0008.C0008I</IndexLocation>
<StreamLocation>^WS.Document.C0008.C0008S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
